# Generated by Django 5.2.4 on 2025-07-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_consultationrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationrequest',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='inquiry_type',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('product', 'Product Information'), ('quote', 'Quote Request'), ('sample', 'Sample Request'), ('partnership', 'Partnership/Business'), ('technical', 'Technical Support'), ('other', 'Other')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
